
#' Concept Set Distribution -- Output Generation
#'
#' Using the tabular output generated by `csd_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_ssdqa()`
#'
#' @param process_output the output from `csd_process`
#' @param output_function the name of the output function that should be executed, provided in the message output
#'                        to the console after `csd_process` has been executed
#' @param concept_set the same concept set used in the `csd_process` function; only required if `vocab_tbl` is not NULL
#' @param vocab_tbl OPTIONAL: the location of an external vocabulary table containing concept names for
#'                  the provided codes. if not NULL, concept names will be available in either a reference
#'                  table or in a hover tooltip
#' @param num_variables an integer to represent the top number of variables to include for the exploratory analyses;
#'                      will pick based on the most commonly appearing variables;
#' @param num_mappings an integer to represent the top number of mappings for a given variable in the exploratory analyses;
#'                     will pick based on the highest count of the most commonly appearing variables;
#' @param filter_variable for both `single- and multi- site anomaly tests without time measurements` and
#'                        `single- and multi- site exploratory tests with time measurements`, the variables
#'                        to focus on
#' @param filter_concept for `ss_anom_la`, `ms_exp_la`, and `ms_anom_la`, the specific code that should
#'                       be the focus of the analysis
#' @param text_wrapping_char an integer to limit the length of text on an axis before wrapping is enforced;
#'                           used in `ms_anom_cs`
#' @param output_value the numerical column in `process_output` that should be used in the visualization
#'                     relevant for `ss_exp_la`, `ms_anom_cs`, and `ms_exp_la`
#'
#' @return a graph to visualize the results from `csd_process` based on the parameters provided; see documentation
#'         for individual subfunctions for details on specific output
#'
#' @export
#'
csd_output <- function(process_output,
                       output_function,
                       concept_set = NULL,
                       vocab_tbl = NULL,
                       num_variables = 10,
                       num_mappings = 10,
                       filter_variable = NULL,
                       filter_concept = NULL,
                       #facet=NULL,
                       text_wrapping_char = 80,
                       output_value = 'prop_concept'){

  ## check concept col
  concept_col <- ifelse('concept_id' %in% colnames(process_output), 'concept_id', 'concept_code')

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  if('concept_id' %in% colnames(process_output)){
    process_output <- process_output %>% mutate(concept_id = as.integer(concept_id))
  }else{process_output <- process_output}

  ## Get concept names from vocabulary table
  if(output_function != 'csd_ss_anom_cs'){

    if(is.null(concept_set)){
      process_output <- process_output
    }else{
      process_output <- process_output %>% inner_join(concept_set)
    }

      process_output <- join_to_vocabulary(tbl = process_output,
                                           vocab_tbl = vocab_tbl,
                                           col = concept_col,
                                           vocab_col = concept_col)
  }

  ## Run output functions
  if(output_function == 'csd_ss_exp_cs'){
    csd_output <- csd_ss_exp_cs(process_output=process_output,
                                concept_col = concept_col,
                                num_codes = num_variables,
                                num_mappings = num_mappings)
  }else if(output_function == 'csd_ss_anom_cs'){
    csd_output <- csd_ss_anom_cs(process_output,
                                 concept_col = concept_col,
                                 vocab_tbl = vocab_tbl,
                                 filtered_var = filter_variable)
  }else if(output_function == 'csd_ss_exp_la'){
    csd_output <- csd_ss_exp_la(process_output,
                                concept_col = concept_col,
                                facet=facet,
                                filtered_var = filter_variable,
                                num_mappings = num_mappings,
                                output_value=output_value)
  }else if(output_function == 'csd_ss_anom_la'){
    csd_output <- csd_ss_anom_la(process_output=process_output,
                                 concept_col = concept_col,
                                 filter_concept = filter_concept,
                                 filtered_var=filter_variable,
                                 facet=facet)
  }else if(output_function == 'csd_ms_exp_cs'){
    csd_output <- csd_ms_exp_cs(process_output=process_output,
                                concept_col = concept_col,
                                facet=facet,
                                num_codes = num_variables)
  }else if(output_function == 'csd_ms_anom_cs'){
    csd_output <- csd_ms_anom_cs(process_output=process_output,
                                 concept_col = concept_col,
                                 text_wrapping_char=text_wrapping_char,
                                 filtered_var=filter_variable,
                                 comparison_col=output_value)
  }else if(output_function == 'csd_ms_exp_la'){
    csd_output <- csd_ms_exp_la(process_output = process_output,
                                concept_col = concept_col,
                                filtered_var = filter_variable,
                                filtered_concept = filter_concept,
                                output_value = output_value,
                                facet = facet
    )
  }else if(output_function == 'csd_ms_anom_la'){
    csd_output <- csd_ms_anom_la(process_output=process_output,
                                 concept_col = concept_col,
                                 filter_concept=filter_concept)
  }else(cli::cli_abort('Please enter a valid output_function for this check'))

  return(csd_output)

}
