
#' Concept Set Distribution -- Output Generation
#'
#' Using the tabular output generated by `csd_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `csd_process`
#'
#' @param concept_set *tabular input* || **optional**
#'
#'   The concept set originally used in the `csd_process` function. Recommended
#'   if no vocab_tbl is provided but the concept names are available in the concept set.
#'
#' @param vocab_tbl *tabular input* || **optional**
#'
#'   A vocabulary table containing concept names for the provided codes
#'   (ex: the OMOP concept table)
#'
#' @param num_variables *integer* || defaults to `30`
#'
#'   An integer indicating the top N of variables to include for the exploratory analyses.
#'   The function will choose the most commonly occurring N variables to include in the plot.
#'
#' @param num_mappings *integer* || defaults to `30`
#'
#'   An integer indicating the top N of concepts to include for the exploratory analyses.
#'   The function will choose the most commonly occurring N concepts per variable
#'   to include in the plot.
#'
#' @param filter_variable *string or vector* || defaults to `NULL`
#'
#'   The specific variable(s) to display in the output. This parameter is required
#'   for the following check types:
#'   - `Single Site, Anomaly Detection, Cross-Sectional`
#'   - `Multi Site, Anomaly Detection, Cross-Sectional`
#'   - `Single Site, Exploratory, Longitudinal`
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'   - `Multi Site, Exploratory, Longitudinal`
#'
#' @param filter_concept *numeric/string or vector* || defaults to `NULL`
#'
#'   The specific code(s) to display in the output. This parameter is required
#'   for the following check types:
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'   - `Multi Site, Exploratory, Longitudinal`
#'   - `Multi Site, Anomaly Detection, Longitudinal`
#'
#' @param text_wrapping_char *integer* || defaults to `80`
#'
#'   An integer indicating the length limit for text on an axis before
#'   wrapping is enforced. This is only used for the
#'   `Multi Site, Anomaly Detection, Cross-Sectional` check type
#'
#' @param output_value *string* || defaults to `prop_concept`
#'
#'   The name of the numerical column in `process_output` that should be
#'   used in the output. This parameter is required for the following check
#'   types:
#'   - `Multi-Site, Anomaly Detection, Cross-Sectional`
#'   - `Single Site, Exploratory, Longitudinal`
#'   - `Multi-Site, Exploratory, Longitudinal`
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `csd_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-csd_process_output.R
#'
#' @export
#'
csd_output <- function(process_output,
                       # output_function,
                       concept_set = NULL,
                       vocab_tbl = NULL,
                       num_variables = 10,
                       num_mappings = 10,
                       filter_variable = NULL,
                       filter_concept = NULL,
                       #facet=NULL,
                       text_wrapping_char = 80,
                       output_value = 'prop_concept',
                       large_n = FALSE,
                       large_n_sites = NULL){

  ## extract output function
  output_function <- process_output %>% collect() %>% distinct(output_function) %>% pull()

  ## check concept col
  concept_col <- ifelse('concept_id' %in% colnames(process_output), 'concept_id', 'concept_code')

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  if('concept_id' %in% colnames(process_output)){
    process_output <- process_output %>% mutate(concept_id = as.integer(concept_id))
  }else{process_output <- process_output}

  ## Get concept names from vocabulary table
  if(output_function != 'csd_ss_anom_cs'){

    if(is.null(concept_set)){
      process_output <- process_output
    }else{
      process_output <- process_output %>% inner_join(concept_set)
    }

      process_output <- join_to_vocabulary(tbl = process_output,
                                           vocab_tbl = vocab_tbl,
                                           col = concept_col,
                                           vocab_col = concept_col)
  }

  ## Run output functions
  if(output_function == 'csd_ss_exp_cs'){
    csd_output <- csd_ss_exp_cs(process_output=process_output,
                                concept_col = concept_col,
                                num_codes = num_variables,
                                num_mappings = num_mappings)
  }else if(output_function == 'csd_ss_anom_cs'){
    csd_output <- csd_ss_anom_cs(process_output,
                                 #concept_col = concept_col,
                                 vocab_tbl = vocab_tbl,
                                 filtered_var = filter_variable)
  }else if(output_function == 'csd_ss_exp_la'){
    csd_output <- csd_ss_exp_la(process_output,
                                concept_col = concept_col,
                                facet=facet,
                                filtered_var = filter_variable,
                                num_mappings = num_mappings,
                                output_value=output_value)
  }else if(output_function == 'csd_ss_anom_la'){
    csd_output <- csd_ss_anom_la(process_output=process_output,
                                 concept_col = concept_col,
                                 filter_concept = filter_concept,
                                 filtered_var=filter_variable,
                                 facet=facet)
  }else if(output_function == 'csd_ms_exp_cs'){
    csd_output <- csd_ms_exp_cs(process_output=process_output,
                                concept_col = concept_col,
                                facet=facet,
                                num_codes = num_variables,
                                large_n = large_n,
                                large_n_sites = large_n_sites)
  }else if(output_function == 'csd_ms_anom_cs'){
    csd_output <- csd_ms_anom_cs(process_output=process_output,
                                 concept_col = concept_col,
                                 text_wrapping_char=text_wrapping_char,
                                 filtered_var=filter_variable,
                                 comparison_col=output_value,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)
  }else if(output_function == 'csd_ms_exp_la'){
    csd_output <- csd_ms_exp_la(process_output = process_output,
                                concept_col = concept_col,
                                filtered_var = filter_variable,
                                filtered_concept = filter_concept,
                                output_value = output_value,
                                facet = facet,
                                large_n = large_n,
                                large_n_sites = large_n_sites)
  }else if(output_function == 'csd_ms_anom_la'){
    csd_output <- csd_ms_anom_la(process_output=process_output,
                                 concept_col = concept_col,
                                 filter_concept=filter_concept,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)
  }else(cli::cli_abort('Please enter a valid output_function for this check'))

  return(csd_output)

}
