

utils::globalVariables(c('site', 'person_id', 'patid', 'start_date', 'end_date',
                         'fu', 'age_grp', 'anomaly_yn', 'x', 'y', 'lcl', 'ucl',
                         'cl', 'anomaly_yn', 'cocount', 'concept1',
                         'concept1_ct', 'concept2', 'concept2_ct',
                         'dist_eucl_mean', 'dist_mean', 'dist_mean_sum',
                         'facet_col', 'jaccard_index', 'mad_val',
                         'mean_allsiteprop', 'mean_site_loess', 'mean_val',
                         'median_val', 'n_grp', 'name', 'name2', 'overall_sd',
                         'prop_col', 'sd_val', 'text_raw', 'text_smooth',
                         'time_end', 'time_increment', 'time_start', 'tooltip',
                         'total_pt_ct', 'total_row_ct', 'value', 'value2',
                         'variable', 'variable_pt_ct', 'variable_row_ct', 'ycol',
                         'site_loess', 'above_sd', 'concept', 'concept_code',
                         'concept_field', 'concept_id', 'concept_name',
                         'conceptname1', 'conceptname2', 'ct_concept', 'ct_denom',
                         'date_field', 'domain', 'nmap', 'prop_concept', 'total_sum',
                         'var_jaccard_mean', 'var_jaccard_sd', 'vocabulary_field',
                         'xaxis', 'q1', 'q3', 'site_anoms', 'site_w_anom', 'zscr',
                         'closest_site', 'concept_id_label', 'delim', 'farthest_site',
                         'iqr_val', 'nvar', 'max_ct', 'min_ct', 'site_range'))
